-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgoqh8HLGD1wYhvpft
bkFwAcFfB9j1faHjdPNykxu/OqugCgYIKoZIzj0DAQehRANCAAReDlPgLWhM4JZ0
KbjKS3yvfrjUKt0QA7d3BmWoWcNb6kAucKcECujNUWC82ETq2loAy+H/p+RoYoru
9M4EJGVX
-----END PRIVATE KEY-----